### ISSUE TITLE
Artifact Store Unable to Extract Downloads on Linux, Windows

### ISSUE THREAD

**Issue by michaelahlers** [michaelahlers/embedded-phantom#22]
On Linux (see [build 85.1](https://travis-ci.org/michaelahlers/embedded-phantom/jobs/153660803#L665)):

```
[info] PhantomSpec:
[info] - must start V211, and receive commands *** FAILED ***
[info]   java.lang.NullPointerException:
[info]   at java.io.FileInputStream.<init>(FileInputStream.java:138)
[info]   at de.flapdoodle.embed.process.extract.Tbz2Extractor.archiveStream(Tbz2Extractor.java:39)
[info]   at de.flapdoodle.embed.process.extract.AbstractExtractor.archiveStreamWithExceptionHint(AbstractExtractor.java:47)
[info]   at de.flapdoodle.embed.process.extract.AbstractExtractor.extract(AbstractExtractor.java:66)
[info]   at de.flapdoodle.embed.process.store.ArtifactStore.extractFileSet(ArtifactStore.java:79)
[info]   at de.flapdoodle.embed.process.store.ExtractedArtifactStore.extractFileSet(ExtractedArtifactStore.java:103)
[info]   at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:57)
[info]   at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:49)
[info]   at ahlers.phantom.embedded.PhantomSpec$$anonfun$1$$anonfun$apply$1.apply$mcV$sp(PhantomSpec.scala:54)
[info]   at ahlers.phantom.embedded.PhantomSpec$$anonfun$1$$anonfun$apply$1.apply(PhantomSpec.scala:24)
[info]   ...
```

On Windows (see [build 77](https://ci.appveyor.com/project/michaelahlers/embedded-phantom/build/77/job/jla9ra04mjxtin3q#L548)):

```
[info] PhantomSpec:
[info] - must start V211, and receive commands *** FAILED ***
[info]   java.lang.NullPointerException:
[info]   at org.apache.commons.compress.archivers.zip.ZipFile.<init>(ZipFile.java:209)
[info]   at org.apache.commons.compress.archivers.zip.ZipFile.<init>(ZipFile.java:192)
[info]   at org.apache.commons.compress.archivers.zip.ZipFile.<init>(ZipFile.java:153)
[info]   at de.flapdoodle.embed.process.extract.ZipExtractor.archiveStream(ZipExtractor.java:42)
[info]   at de.flapdoodle.embed.process.extract.AbstractExtractor.archiveStreamWithExceptionHint(AbstractExtractor.java:47)
[info]   at de.flapdoodle.embed.process.extract.AbstractExtractor.extract(AbstractExtractor.java:66)
[info]   at de.flapdoodle.embed.process.store.ArtifactStore.extractFileSet(ArtifactStore.java:79)
[info]   at de.flapdoodle.embed.process.store.ExtractedArtifactStore.extractFileSet(ExtractedArtifactStore.java:103)
[info]   at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:57)
[info]   at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:49)
[info]   ...
```

**Comment by michaelahlers** [comment]
A call to `de.flapdoodle.embed.process.store.LocalArtifactStore#getArtifact` by `de.flapdoodle.embed.process.store.ArtifactStore#extractFileSet` returns `null`.

**Comment by michaelahlers** [comment]
`LocalArtifactStore#getArtifact` reliably fails when `IDownloadConfig.getArtifactStorePath` is a randomly-generated path (_i.e._, `de.flapdoodle.embed.process.io.directories.IDirectory#isGenerated` returns `true`). To date, `TempDirInPlatformTempDir` has been used to avoid resource conflicts in CI, but that prevents discovery of temporary download files.

**Comment by michaelahlers** [comment]
Tests now direct artifacts to random-but-stable locations, and nested within the JVM's `user.home`. Paths are timestamped and logged to help with debugging.

This resolves two issues:

1. Inability of `LocalArtifactStore#getArtifact` to discover downloaded artifacts (because `IDirectory#asFile` in `_downloadConfig` now returns consistent values).
1. Permission problems on Travis CI.

What remains unclear is why binaries are still deployed to the platform's temporary directory (_.e.g._, `/tmp/temp--dddf905f-c80f-4536-bae7-b601a114f796/extract-travis-extractphantomjs` on Travis CI), despite `extractDir` having been assigned to a location in the home.
